services:
  - type: web
    name: dsdeliver-backend
    plan: free
    preBuildCommand: sudo apt-get update && sudo apt-get install -y openjdk-17-jdk && chmod +x Backend/mvnw
    buildCommand: cd Backend && bash ./mvnw clean package -DskipTests
    startCommand: java -jar Backend/target/dsdeliver-0.0.1-SNAPSHOT.jar
    envVars:
      - key: DATABASE_URL
        value: jdbc:postgresql://dsdeliver_owner:npg_mkMDrCUH5JK1@ep-fancy-pine-acrmni8x-pooler.sa-east-1.aws.neon.tech:5432/dsdeliver?sslmode=require
